In [1]:
import pandas as pd

In [7]:
data1 = pd.read_csv(r"C:\Users\apkar\OneDrive\Documents\iGEM\Head\Linker design\uniprotkb_ec_3_4_21_AND_length_450_TO_5_2026_04_14.tsv\uniprotkb_ec_3_4_21_AND_length_450_TO_5_2026_04_14.tsv", sep = '\t')

In [7]:
asp = pd.read_csv(r"C:\Users\apkar\OneDrive\Documents\iGEM\Head\Linker design\Aspatic Protease.txt", sep = '\t')

In [8]:
asp

,MEROPS ID,Peptidase,Total substrates,Physiological substrates,Non-physiological substrates
0,A01.001,pepsin A,970,21,949
1,A01.002,pepsin B,25,1,24
2,A01.003,gastricsin,50,6,44
3,A01.004,BACE1 g.p. (Homo sapiens),25,16,9
4,A01.006,chymosin,20,11,9
...,...,...,...,...,...
297,A9G.010,pycnoporopepsin,8,0,8
298,A9G.017,acid peptidase (Cladosporium),8,0,8
299,A9G.018,acid peptidase (Paecilomyces),0,0,0
300,A9G.019,acrocylindropepsin,6,0,6
301,A9G.020,yapsin A,9,0,9

In [10]:
mer = asp['MEROPS ID']

In [12]:
import requests
import pandas as pd
import time
import re
from bs4 import BeautifulSoup


# ============================================================
# INPUT
# ============================================================

# Your existing list:
#
# mer = [
#     "S01.001",
#     "S01.002",
#     "M01.001",
#     ...
# ]


# ============================================================
# SETTINGS
# ============================================================

MEROPS_URL = "https://www.ebi.ac.uk/merops/cgi-bin/substrates"
UNIPROT_URL = "https://rest.uniprot.org/uniprotkb/{}.fasta"

WINDOW = 10
MEROPS_DELAY = 1.0


# ============================================================
# SESSION
# ============================================================

session = requests.Session()

session.headers.update({
    "User-Agent": "Mozilla/5.0 Protease-substrate research"
})


# ============================================================
# CACHE
# ============================================================

merops_cache = {}
sequence_cache = {}


# ============================================================
# GET MEROPS SUBSTRATE TABLE
# ============================================================

def get_merops_substrates(merops_id):

    if merops_id in merops_cache:
        return merops_cache[merops_id]

    try:

        response = session.get(
            MEROPS_URL,
            params={"id": merops_id},
            timeout=60
        )

        response.raise_for_status()

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        tables = soup.find_all("table")

        for table in tables:

            rows = table.find_all("tr")

            if not rows:
                continue

            headers = [
                cell.get_text(" ", strip=True)
                for cell in rows[0].find_all(
                    ["th", "td"]
                )
            ]

            # Find the substrate table
            substrate_column = None

            for i, header in enumerate(headers):

                if "substrate" in header.lower():

                    substrate_column = i
                    break

            if substrate_column is None:
                continue

            data = []

            for row in rows[1:]:

                cells = [
                    cell.get_text(" ", strip=True)
                    for cell in row.find_all(
                        ["td", "th"]
                    )
                ]

                if len(cells) <= substrate_column:
                    continue

                # Keep the complete row
                if len(cells) < len(headers):
                    cells += [""] * (
                        len(headers) - len(cells)
                    )

                cells = cells[:len(headers)]

                row_dict = dict(
                    zip(headers, cells)
                )

                data.append(row_dict)

            merops_cache[merops_id] = data

            return data

        merops_cache[merops_id] = []

        return []

    except Exception as e:

        print(
            f"MEROPS ERROR {merops_id}: {e}"
        )

        merops_cache[merops_id] = []

        return []


# ============================================================
# GENERIC COLUMN FINDER
# ============================================================

def get_column(row, possible_names):

    normalized = {}

    for key in row.keys():

        clean = re.sub(
            r"[^a-z0-9]",
            "",
            str(key).lower()
        )

        normalized[clean] = key

    for name in possible_names:

        clean = re.sub(
            r"[^a-z0-9]",
            "",
            name.lower()
        )

        if clean in normalized:

            value = row[normalized[clean]]

            if value is not None:
                return str(value).strip()

    return ""


# ============================================================
# GET SUBSTRATE UniProt ID
# ============================================================

def get_substrate_uniprot(row):

    value = get_column(
        row,
        [
            "UniProt",
            "Uniprot",
            "UniProt ID",
            "UniProt accession",
            "Accession"
        ]
    )

    # Some MEROPS entries may contain additional text.
    # Try to extract a standard UniProt accession.

    match = re.search(
        r"\b[A-NR-Z][0-9][A-Z0-9]{3}[0-9]\b",
        value
    )

    if match:
        return match.group(0)

    return value


# ============================================================
# GET SUBSTRATE SEQUENCE FROM UniProt
# ============================================================

def get_uniprot_sequence(uniprot_id):

    if not uniprot_id:
        return None

    if uniprot_id in sequence_cache:
        return sequence_cache[uniprot_id]

    try:

        # Remove isoform suffix if present
        # e.g. P12345-2 -> P12345
        base_id = uniprot_id.split("-")[0]

        url = UNIPROT_URL.format(
            base_id
        )

        response = session.get(
            url,
            timeout=60
        )

        if response.status_code != 200:

            sequence_cache[uniprot_id] = None

            return None

        sequence = "".join(
            line.strip()
            for line in response.text.splitlines()
            if not line.startswith(">")
        )

        sequence_cache[
            uniprot_id
        ] = sequence

        return sequence

    except Exception as e:

        print(
            f"UniProt ERROR {uniprot_id}: {e}"
        )

        sequence_cache[
            uniprot_id
        ] = None

        return None


# ============================================================
# PARSE CLEAVAGE POSITION
# ============================================================

def parse_cleavage_position(cleavage_site):

    if not cleavage_site:
        return None

    # Examples:
    #
    # Gly373+Ala
    # Arg195+Ser
    # Lys1754+Ser
    #
    # The number corresponds to P1.

    match = re.search(
        r"[A-Za-z]{1,3}[- ]?(\d+)\s*\+",
        cleavage_site
    )

    if match:

        return int(
            match.group(1)
        )

    return None


# ============================================================
# EXTRACT ±10 AA WINDOW
# ============================================================

def get_binding_window(
    sequence,
    cleavage_position,
    window=10
):

    if (
        not sequence
        or cleavage_position is None
    ):
        return None

    # MEROPS uses 1-based residue numbering.
    #
    # If cleavage is:
    #
    # residue 100 | residue 101
    #       P1    |    P1'
    #
    # Python cleavage boundary = index 100

    cut_index = cleavage_position

    left = max(
        0,
        cut_index - window
    )

    right = min(
        len(sequence),
        cut_index + window
    )

    region = sequence[
        left:right
    ]

    marker = cut_index - left

    return (
        region[:marker]
        + "|"
        + region[marker:]
    )


# ============================================================
# MAIN LOOP
# ============================================================

results = []

failed_merops = []

for i, merops_id in enumerate(
    mer,
    start=1
):

    print(
        f"[{i}/{len(mer)}] {merops_id}"
    )

    # --------------------------------------------------------
    # Get substrate records
    # --------------------------------------------------------

    substrates = get_merops_substrates(
        merops_id
    )

    print(
        f"    {len(substrates)} substrate records"
    )

    if not substrates:
        failed_merops.append(
            merops_id
        )

    # --------------------------------------------------------
    # Process every substrate
    # --------------------------------------------------------

    for substrate in substrates:

        # ----------------------------------------------------
        # Substrate information
        # ----------------------------------------------------

        substrate_name = get_column(
            substrate,
            [
                "Substrate",
                "Substrate name"
            ]
        )

        substrate_uniprot = (
            get_substrate_uniprot(
                substrate
            )
        )

        # ----------------------------------------------------
        # Cleavage site
        # ----------------------------------------------------

        cleavage_site = get_column(
            substrate,
            [
                "Cleavage Site",
                "Cleavage",
                "Site"
            ]
        )

        # ----------------------------------------------------
        # Get full substrate sequence
        # ----------------------------------------------------

        substrate_sequence = None

        if substrate_uniprot:

            substrate_sequence = (
                get_uniprot_sequence(
                    substrate_uniprot
                )
            )

        # ----------------------------------------------------
        # Synthetic substrate
        #
        # If there is no UniProt sequence, look for a
        # sequence directly in the MEROPS record.
        # ----------------------------------------------------

        if not substrate_sequence:

            substrate_sequence = get_column(
                substrate,
                [
                    "Sequence",
                    "Substrate sequence",
                    "Peptide sequence"
                ]
            )

            if not substrate_sequence:
                substrate_sequence = None

        # ----------------------------------------------------
        # Cleavage position
        # ----------------------------------------------------

        cleavage_position = (
            parse_cleavage_position(
                cleavage_site
            )
        )

        # ----------------------------------------------------
        # ±10 AA sequence
        # ----------------------------------------------------

        binding_window = (
            get_binding_window(
                substrate_sequence,
                cleavage_position,
                WINDOW
            )
        )

        # ----------------------------------------------------
        # Store result
        # ----------------------------------------------------

        results.append({

            "merops_id":
                merops_id,

            "substrate":
                substrate_name,

            "substrate_uniprot":
                substrate_uniprot,

            "substrate_sequence":
                substrate_sequence,

            "cleavage_site":
                cleavage_site,

            "cleavage_position":
                cleavage_position,

            "binding_window_±10":
                binding_window
        })

    # --------------------------------------------------------
    # Delay before next MEROPS request
    # --------------------------------------------------------

    time.sleep(
        MEROPS_DELAY
    )


# ============================================================
# CREATE DATAFRAME
# ============================================================

df = pd.DataFrame(
    results
)


# ============================================================
# SAVE
# ============================================================

df.to_csv(
    "merops_substrates_with_window10.csv",
    index=False
)


# ============================================================
# SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("FINISHED")
print("=" * 70)

print(
    "MEROPS IDs:",
    len(mer)
)

print(
    "Total substrate records:",
    len(df)
)

print(
    "Records with substrate sequence:",
    df["substrate_sequence"].notna().sum()
)

print(
    "Records with ±10 AA window:",
    df["binding_window_±10"].notna().sum()
)

print(
    "MEROPS IDs with no substrate records:",
    len(failed_merops)
)

print(
    "\nCSV:",
    "merops_substrates_with_window10.csv"
)

display(
    df.head(20)
)

[1/302] A01.001
    970 substrate records
[2/302] A01.002
    25 substrate records
[3/302] A01.003
    50 substrate records
[4/302] A01.004
    25 substrate records
[5/302] A01.006
    20 substrate records
[6/302] A01.007
    10 substrate records
[7/302] A01.008
    3 substrate records
[8/302] A01.009
    924 substrate records
[9/302] A01.010
    1596 substrate records
UniProt ERROR Q99LD4: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
[10/302] A01.011
    17 substrate records
[11/302] A01.012
    249 substrate records
[12/302] A01.013
    9 substrate records
[13/302] A01.014
    26 substrate records
[14/302] A01.015
    1 substrate records
[15/302] A01.016
    157 substrate records
[16/302] A01.017
    11 substrate records
[17/302] A01.018
    14 substrate records
[18/302] A01.019
    11 substrate records
[19/302] A01.020
    62 substrate records
[20/302] A01.021
    5 substrate records
[21/302] A01.022
    13 substrate records
[22/302] A01.023
    15 substrate records
[23/302] A01.026
    0 substrate records
[24/302] A01.027
    1 substrate records
[25/302] A01.028
    0 substrate records
[26/302] A01.030
    46 substrate records
[27/302] A01.031
    16 substrate records
[28/302] A01.035
    9 substrate records
[29/302] A01.036
    3 substrate records
[30/302] A01.037
    9 substrate records
[31/302] A01.038
    5 substrate records
[32/302] A01.040
    733 substrate records
[33/302] A01.041
    33 substrate records
[34/302] A01.042
    18 substrate records
[35/302] A01.043
    4 substrate records
[36/302] A01.044
    0 substrate records
[37/302] A01.045
    1 substrate records
[38/302] A01.046
    7 substrate records
[39/302] A01.050
    0 substrate records
[40/302] A01.051
    3 substrate records
[41/302] A01.052
    0 substrate records
[42/302] A01.053
    133 substrate records
[43/302] A01.054
    2 substrate records
[44/302] A01.055
    1 substrate records
[45/302] A01.056
    3 substrate records
[46/302] A01.057
    0 substrate records
[47/302] A01.058
    0 substrate records
[48/302] A01.059
    8 substrate records
[49/302] A01.060
    22 substrate records
[50/302] A01.061
    21 substrate records
[51/302] A01.062
    0 substrate records
[52/302] A01.063
    0 substrate records
[53/302] A01.064
    22 substrate records
[54/302] A01.065
    0 substrate records
[55/302] A01.066
    0 substrate records
[56/302] A01.067
    17 substrate records
[57/302] A01.068
    45 substrate records
[58/302] A01.069
    2 substrate records
[59/302] A01.070
    4 substrate records
[60/302] A01.071
    10 substrate records
[61/302] A01.073
    1 substrate records
[62/302] A01.074
    0 substrate records
[63/302] A01.075
    7 substrate records
[64/302] A01.076
    7 substrate records
[65/302] A01.077
    0 substrate records
[66/302] A01.078
    0 substrate records
[67/302] A01.079
    0 substrate records
[68/302] A01.080
    0 substrate records
[69/302] A01.081
    0 substrate records
[70/302] A01.082
    0 substrate records
[71/302] A01.083
    0 substrate records
[72/302] A01.084
    17 substrate records
[73/302] A01.085
    16 substrate records
[74/302] A01.086
    0 substrate records
[75/302] A01.087
    0 substrate records
[76/302] A01.088
    2 substrate records
[77/302] A01.089
    1 substrate records
[78/302] A01.092
    0 substrate records
[79/302] A01.093
    2 substrate records
[80/302] A01.094
    1 substrate records
[81/302] A01.095
    5 substrate records
[82/302] A01.096
    1 substrate records
[83/302] A01.097
    1 substrate records
[84/302] A01.098
    1 substrate records
[85/302] A01.099
    0 substrate records
[86/302] A01.A01
    0 substrate records
[87/302] A01.A02
    0 substrate records
[88/302] A01.A03
    0 substrate records
[89/302] A01.A04
    0 substrate records
[90/302] A01.A05
    0 substrate records
[91/302] A01.A06
    0 substrate records
[92/302] A01.A07
    0 substrate records
[93/302] A01.A08
    0 substrate records
[94/302] A01.A09
    0 substrate records
[95/302] A01.A10
    0 substrate records
[96/302] A01.A11
    0 substrate records
[97/302] A01.A12
    0 substrate records
[98/302] A01.A13
    0 substrate records
[99/302] A01.A14
    0 substrate records
[100/302] A01.A15
    0 substrate records
[101/302] A01.A16
    0 substrate records
[102/302] A01.A17
    0 substrate records
[103/302] A01.A18
    0 substrate records
[104/302] A01.A19
    0 substrate records
[105/302] A01.A20
    0 substrate records
[106/302] A01.A21
    0 substrate records
[107/302] A01.A22
    0 substrate records
[108/302] A01.A23
    0 substrate records
[109/302] A01.A24
    0 substrate records
[110/302] A01.A25
    0 substrate records
[111/302] A01.A26
    0 substrate records
[112/302] A01.A27
    0 substrate records
[113/302] A01.A28
    0 substrate records
[114/302] A01.A29
    0 substrate records
[115/302] A01.A30
    0 substrate records
[116/302] A01.A31
    0 substrate records
[117/302] A01.A32
    0 substrate records
[118/302] A01.A33
    0 substrate records
[119/302] A01.A34
    0 substrate records
[120/302] A01.A35
    0 substrate records
[121/302] A01.A36
    0 substrate records
[122/302] A01.A37
    0 substrate records
[123/302] A01.A38
    0 substrate records
[124/302] A01.A39
    0 substrate records
[125/302] A01.A40
    0 substrate records
[126/302] A01.A41
    0 substrate records
[127/302] A01.A42
    0 substrate records
[128/302] A01.A43
    0 substrate records
[129/302] A01.A44
    0 substrate records
[130/302] A01.A45
    0 substrate records
[131/302] A01.A46
    0 substrate records
[132/302] A01.A47
    0 substrate records
[133/302] A01.A48
    0 substrate records
[134/302] A01.A49
    0 substrate records
[135/302] A01.A50
    0 substrate records
[136/302] A01.A51
    0 substrate records
[137/302] A01.A52
    0 substrate records
[138/302] A01.A53
    0 substrate records
[139/302] A01.A54
    0 substrate records
[140/302] A01.A55
    0 substrate records
[141/302] A01.A56
    0 substrate records
[142/302] A01.A57
    0 substrate records
[143/302] A01.A58
    0 substrate records
[144/302] A01.A59
    0 substrate records
[145/302] A01.A60
    0 substrate records
[146/302] A01.A62
    0 substrate records
[147/302] A01.A63
    0 substrate records
[148/302] A01.A64
    0 substrate records
[149/302] A01.A65
    0 substrate records
[150/302] A01.A66
    0 substrate records
[151/302] A01.A67
    0 substrate records
[152/302] A01.A68
    0 substrate records
[153/302] A01.A69
    0 substrate records
[154/302] A01.A70
    0 substrate records
[155/302] A01.A71
    0 substrate records
[156/302] A01.A72
    0 substrate records
[157/302] A01.A73
    0 substrate records
[158/302] A01.A74
    0 substrate records
[159/302] A01.A75
    0 substrate records
[160/302] A01.A76
    0 substrate records
[161/302] A01.A77
    0 substrate records
[162/302] A01.A78
    0 substrate records
[163/302] A01.A79
    0 substrate records
[164/302] A01.A81
    0 substrate records
[165/302] A01.A82
    0 substrate records
[166/302] A01.A83
    0 substrate records
[167/302] A01.A84
    0 substrate records
[168/302] A01.A85
    0 substrate records
[169/302] A01.A86
    0 substrate records
[170/302] A01.A87
    0 substrate records
[171/302] A01.A88
    0 substrate records
[172/302] A01.A89
    0 substrate records
[173/302] A01.A90
    0 substrate records
[174/302] A01.A91
    0 substrate records
[175/302] A01.A92
    0 substrate records
[176/302] A01.A93
    0 substrate records
[177/302] A01.A94
    0 substrate records
[178/302] A01.A95
    0 substrate records
[179/302] A01.A96
    0 substrate records
[180/302] A02.001
    1046 substrate records
[181/302] A02.002
    30 substrate records
[182/302] A02.003
    0 substrate records
[183/302] A02.004
    13 substrate records
[184/302] A02.005
    11 substrate records
[185/302] A02.006
    0 substrate records
[186/302] A02.007
    28 substrate records
[187/302] A02.008
    20 substrate records
[188/302] A02.009
    18 substrate records
[189/302] A02.010
    13 substrate records
[190/302] A02.011
    100 substrate records
[191/302] A02.012
    15 substrate records
[192/302] A02.013
    20 substrate records
[193/302] A02.015
    18 substrate records
[194/302] A02.016
    7 substrate records
[195/302] A02.018
    0 substrate records
[196/302] A02.019
    0 substrate records
[197/302] A02.020
    6 substrate records
[198/302] A02.021
    0 substrate records
[199/302] A02.022
    5 substrate records
[200/302] A02.024
    1 substrate records
[201/302] A02.051
    0 substrate records
[202/302] A02.052
    0 substrate records
[203/302] A02.053
    0 substrate records
[204/302] A02.054
    0 substrate records
[205/302] A02.055
    0 substrate records
[206/302] A02.056
    0 substrate records
[207/302] A02.057
    0 substrate records
[208/302] A02.060
    0 substrate records
[209/302] A02.061
    6 substrate records
[210/302] A02.062
    0 substrate records
[211/302] A02.063
    25 substrate records
[212/302] A03.001
    1 substrate records
[213/302] A03.002
    6 substrate records
[214/302] A03.003
    0 substrate records
[215/302] A03.004
    0 substrate records
[216/302] A03.005
    0 substrate records
[217/302] A03.006
    0 substrate records
[218/302] A05.001
    18 substrate records
[219/302] A08.001
    5 substrate records
[220/302] A09.001
    11 substrate records
[221/302] A11.001
    9 substrate records
[222/302] A11.002
    0 substrate records
[223/302] A11.003
    3 substrate records
[224/302] A11.004
    0 substrate records
[225/302] A11.005
    0 substrate records
[226/302] A11.051
    0 substrate records
[227/302] A22.001
    19 substrate records
[228/302] A22.002
    0 substrate records
[229/302] A22.003
    6 substrate records
[230/302] A22.004
    5 substrate records
[231/302] A22.005
    0 substrate records
[232/302] A22.006
    0 substrate records
[233/302] A22.007
    5 substrate records
[234/302] A22.008
    0 substrate records
[235/302] A22.009
    0 substrate records
[236/302] A22.010
    0 substrate records
[237/302] A22.012
    0 substrate records
[238/302] A22.013
    0 substrate records
[239/302] A22.014
    0 substrate records
[240/302] A22.015
    8 substrate records
[241/302] A22.A01
    0 substrate records
[242/302] A22.A02
    0 substrate records
[243/302] A22.A03
    0 substrate records
[244/302] A22.A04
    0 substrate records
[245/302] A22.A05
    0 substrate records
[246/302] A22.A06
    0 substrate records
[247/302] A22.A07
    0 substrate records
[248/302] A22.A08
    0 substrate records
[249/302] A22.A09
    0 substrate records
[250/302] A22.A10
    0 substrate records
[251/302] A22.A11
    0 substrate records
[252/302] A22.A12
    0 substrate records
[253/302] A22.A13
    0 substrate records
[254/302] A22.A14
    0 substrate records
[255/302] A22.A15
    0 substrate records
[256/302] A24.001
    16 substrate records
[257/302] A24.003
    0 substrate records
[258/302] A24.016
    6 substrate records
[259/302] A24.017
    18 substrate records
[260/302] A24.018
    2 substrate records
[261/302] A24.019
    0 substrate records
[262/302] A24.A01
    0 substrate records
[263/302] A24.A10
    0 substrate records
[264/302] A25.001
    32 substrate records
[265/302] A26.001
    54 substrate records
[266/302] A26.002
    11 substrate records
[267/302] A26.003
    16 substrate records
[268/302] A26.004
    2 substrate records
[269/302] A26.005
    1 substrate records
[270/302] A28.001
    0 substrate records
[271/302] A28.002
    0 substrate records
[272/302] A28.003
    0 substrate records
[273/302] A28.004
    15 substrate records
[274/302] A28.A01
    0 substrate records
[275/302] A28.A02
    0 substrate records
[276/302] A28.A03
    0 substrate records
[277/302] A28.A04
    0 substrate records
[278/302] A28.A05
    0 substrate records
[279/302] A28.A06
    0 substrate records
[280/302] A28.A07
    0 substrate records
[281/302] A28.A08
    0 substrate records
[282/302] A28.A09
    0 substrate records
[283/302] A28.A10
    0 substrate records
[284/302] A31.001
    4 substrate records
[285/302] A31.002
    0 substrate records
[286/302] A31.003
    1 substrate records
[287/302] A31.004
    0 substrate records
[288/302] A31.005
    1 substrate records
[289/302] A31.006
    1 substrate records
[290/302] A31.007
    0 substrate records
[291/302] A31.008
    0 substrate records
[292/302] A32.001
    0 substrate records
[293/302] A32.002
    800 substrate records
[294/302] A36.001
    4 substrate records
[295/302] A37.001
    6 substrate records
[296/302] A39.001
    4 substrate records
[297/302] A9G.001
    0 substrate records
[298/302] A9G.010
    8 substrate records
[299/302] A9G.017
    8 substrate records
[300/302] A9G.018
    0 substrate records
[301/302] A9G.019
    6 substrate records
[302/302] A9G.020
    9 substrate records

======================================================================
FINISHED
======================================================================
MEROPS IDs: 302
Total substrate records: 7956
Records with substrate sequence: 6944
Records with ±10 AA window: 5892
MEROPS IDs with no substrate records: 187

CSV: merops_substrates_with_window10.csv

,merops_id,substrate,substrate_uniprot,substrate_sequence,cleavage_site,cleavage_position,binding_window_±10
0,A01.001,ac-Phe-Tyr(I2),,None,ac-Phe+Tyr(I2),NaN,None
1,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Asn7+Lys-peptide,7.0,MSFTLTN|KNVIFVAGLG
2,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Asn9+Val-peptide,9.0,MSFTLTNKN|VIFVAGLGGI
3,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Phe12+Val-peptide,12.0,FTLTNKNVIF|VAGLGGIGLD
4,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Gly18+Ile-peptide,18.0,NVIFVAGLGG|IGLDTSKELL
5,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Gly20+Leu-peptide,20.0,IFVAGLGGIG|LDTSKELLKR
6,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Leu21+Asp-peptide,21.0,FVAGLGGIGL|DTSKELLKRD
7,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Leu28+Lys-peptide,28.0,IGLDTSKELL|KRDLKNLVIL
8,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Leu27+Leu-peptide,27.0,GIGLDTSKEL|LKRDLKNLVI
9,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Arg30+Asp-peptide,30.0,LDTSKELLKR|DLKNLVILDR
10,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Leu32+Lys-peptide,32.0,TSKELLKRDL|KNLVILDRIE
11,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Asn34+Leu-peptide,34.0,KELLKRDLKN|LVILDRIENP
12,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Leu35+Val-peptide,35.0,ELLKRDLKNL|VILDRIENPA
13,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Leu38+Asp-peptide,38.0,KRDLKNLVIL|DRIENPAAIA
14,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Asp39+Arg-peptide,39.0,RDLKNLVILD|RIENPAAIAE
15,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Ala46+Ile-peptide,46.0,ILDRIENPAA|IAELKAINPK
16,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Ile47+Ala-peptide,47.0,LDRIENPAAI|AELKAINPKV
17,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Glu49+Leu-peptide,49.0,RIENPAAIAE|LKAINPKVTV
18,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Ala52+Ile-peptide,52.0,NPAAIAELKA|INPKVTVTFY
19,A01.001,alcohol dehydrogenase,P00334,MSFTLTNKNVIFVAGLGGIGLDTSKELLKRDLKNLVILDRIENPAA...,peptide-Lys51+Ala-peptide,51.0,ENPAAIAELK|AINPKVTVTF

In [14]:
df['binding_window_±10'].nunique()

4543

In [16]:
df.to_csv('Aspatic Protease Substrates.csv')

In [17]:
data1

,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Mass,Sequence,Active site,Binding site,Protein existence,Protein families
0,A0A096N5A4,unreviewed,A0A096N5A4_PAPAN,"Serine protease HTRA2, mitochondrial (EC 3.4.2...",HTRA2,Papio anubis (Olive baboon),458,48746,MAAPRAGRGAGWSLRAWRALGGIRWGRRPRLTPDLRALLTSGTSDP...,NaN,NaN,Inferred from homology,Peptidase S1C family
1,A0A0D9RT82,unreviewed,A0A0D9RT82_CHLSB,"Serine protease HTRA2, mitochondrial (EC 3.4.2...",HTRA2,Chlorocebus sabaeus (Green monkey) (Simia sabaea),458,48755,MAAPRAGRGAGWSLRAWRALGGIRWGRRPRLTPDLRALLTSGTSDP...,NaN,NaN,Inferred from homology,Peptidase S1C family
2,A0A0P6IWL7,unreviewed,A0A0P6IWL7_HETGA,Plasminogen activator (EC 3.4.21.68),PLAT Plat,Heterocephalus glaber (Naked mole rat),562,63557,MRMRQELLCVLLLCGAISTLPSQKTHTRFRRGARSYRVTCRDEKTQ...,"ACT_SITE 357; /note=""Charge relay system""; /ev...",NaN,Inferred from homology,Peptidase S1 family
3,A0A1U7QSP2,unreviewed,A0A1U7QSP2_MESAU,"Serine protease HTRA2, mitochondrial (EC 3.4.2...",Htra2,Mesocricetus auratus (Golden hamster),458,48832,MAALKAGRGAGWSLRAWRALGGIFWGKGPLLTPDLRGLLTSGSPDP...,NaN,NaN,Inferred from homology,Peptidase S1C family
4,A0A286XQ11,unreviewed,A0A286XQ11_CAVPO,"Serine protease HTRA2, mitochondrial (EC 3.4.2...",HTRA2,Cavia porcellus (Guinea pig),455,48645,MAALRAGRGAAWILQGWRALGGILCGKGPLLTPDLRALLTSGTPYL...,NaN,NaN,Inferred from homology,Peptidase S1C family
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42642,X0HJK8,unreviewed,X0HJK8_FUSOX,Serine protease (EC 3.4.21.-),FOPG_08729,Fusarium oxysporum f. sp. conglutinans race 2 ...,577,62150,MMGTGWLIRPDLLVTAGHVVHDWGRKLGPADQIKCYIGYNGKQSVG...,NaN,NaN,Inferred from homology,Peptidase S1B family
42643,X0IUL2,unreviewed,X0IUL2_FUSOX,Serine protease (EC 3.4.21.-),FOPG_08591,Fusarium oxysporum f. sp. conglutinans race 2 ...,589,63911,MASSNPERTYARWSLRDVPHTLATDVLPIGPGADGIETVFDDDSRR...,NaN,NaN,Inferred from homology,Peptidase S1 family; Peptidase S1B family
42644,X0L973,unreviewed,X0L973_FUSOX,Serine protease (EC 3.4.21.-),FOTG_14251,Fusarium oxysporum f. sp. vasinfectum 25433,577,62087,MMGTGWLIRPDLLVTAGHVVHDWGRKLGPADQIKCYIGYNGKQSVG...,NaN,NaN,Inferred from homology,Peptidase S1B family
42645,X5DRZ5,unreviewed,X5DRZ5_9CORY,Putative trypsin-like serine protease (EC 3.4....,pepD CGLY_04870,Corynebacterium glyciniphilum AJ 3170,475,47351,MSGEDRIGNGDDGFSDPRDPRDPRGEQGHQGPGVWGRDGRGSSSPE...,NaN,NaN,Inferred from homology,Peptidase S1C family
42646,X5K8V9,unreviewed,X5K8V9_9FLAO,Protease (EC 3.4.21.107),mucD AYC66_02845 BAY09_06860 CMU51_16490 NCTC1...,Elizabethkingia anophelis,506,54497,MDFKKIMPLAVVGVLSAATTVGTLHYFDSNHDTNGDFNYFHTSRKD...,NaN,NaN,Inferred from homology,Peptidase S1C family

In [16]:
data1['Protein families'].nunique()

109

In [31]:
prot = list(data1['Entry'].unique())

In [32]:
len(prot)

42647

In [2]:
path = r"C:\Users\apkar\Downloads\uniprotkb_serine_merops_substrates_with_sequences.csv"
data = pd.read_csv(path)

In [4]:
data['substrate_sequence'].nunique()

101

In [5]:
data['input_uniprot'].nunique()

822

In [26]:
import numpy as np

In [ ]:
import requests
import pandas as pd
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
#----------------------------------------------------------------------------------------------------------------------
# Add the path for the protease dataframe 

# data1 = pd.read_csv(r"uniprotkb_ec_3_4_21_AND_length_450_TO_5_2026_04_14.tsv", sep = '\t')
# prot = list(data1['Entry'].unique())

#----------------------------------------------------------------------------------------------------------------------
def get_merops_id(uniprot_id):
    url = f"https://rest.uniprot.org/uniprotkb/{uniprot_id}.txt"

    try:
        response = requests.get(url, timeout=10)

        if response.status_code != 200:
            return uniprot_id, None

        merops_ids = []

        for line in response.text.splitlines():
            if line.startswith("DR   MEROPS;"):
                parts = line.split(";")
                if len(parts) > 1:
                    merops_ids.append(parts[1].strip().rstrip("."))

        return uniprot_id, "; ".join(merops_ids) if merops_ids else None

    except Exception:
        return uniprot_id, None


# Your UniProt IDs
uniprot_ids = prot

results = []

# Number of simultaneous requests
MAX_WORKERS = 10

with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:

    futures = [
        executor.submit(get_merops_id, uid)
        for uid in uniprot_ids
    ]

    for future in tqdm(
        as_completed(futures),
        total=len(futures),
        desc="Getting MEROPS IDs"
    ):
        results.append(future.result())


# Convert results to DataFrame
merops_df = pd.DataFrame(
    results,
    columns=["UniProt_ID", "MEROPS_ID"]
)

# Add MEROPS IDs back to your original dataframe

Getting MEROPS IDs: 100%|██████████| 42647/42647 [6:58:40<00:00,  1.70it/s]

In [36]:
l = len(merops_df)
l2 = len(merops_df.dropna())
print('Numeber of Proteases with MEROPS ID : ' ,l2)
print('Percentage of Proteases with MEROPS ID : ' , l2 * 100/l, '%')

Numeber of Proteases with MEROPS ID :  1220
Percentage of Proteases with MEROPS ID :  2.860693600956691 %

In [37]:
filtered = merops_df.dropna()

In [41]:
filtered.to_csv(r'C:\Users\apkar\OneDrive\Documents\iGEM\Head\Linker design\Protease_merops.csv')

In [4]:
merops = pd.read_csv(r'C:\Users\apkar\OneDrive\Documents\iGEM\Head\Linker design\Protease_merops.csv')

In [2]:
ser = pd.read_csv(r"C:\Users\apkar\OneDrive\Documents\iGEM\Head\Linker design\hip1_similarity_final compiled.csv")

In [5]:
merops

      Unnamed: 0 UniProt_ID MEROPS_ID
0             57     A0JNK3   S01.278
1             60     A6YFB5   S01.277
2             61     F6UNS8   S01.278
3             63     B0BNB9   S01.278
4             64     G1PU69   S01.278
...          ...        ...       ...
1215       42622     V9W7L2   S55.001
1216       42624     W5SHP2   S01.525
1217       42628     W5SMW8   S41.013
1218       42632     W5SZQ1   S41.013
1219       42636     W8U929   S49.001

[1220 rows x 3 columns]

In [3]:
ser

,rank,accession,length,C,best_band,AAAA,AAAD,AADA,AADD,ADAA,...,ADDA,ADDD,DAAA,DAAD,DADA,DADD,DDAA,DDAD,DDDA,DDDD
0,1,P65824,520,1.000000,AAAD,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,2,P9WHR3,520,1.000000,AAAD,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2,3,A0A097R7X2,525,0.742027,AAAA,0.742027,0.308359,0.396374,0.371211,0.437498,...,0.336528,0.331605,0.316790,0.410445,0.359452,0.327044,0.442840,0.400604,0.274666,0.495306
3,4,D5RI84,475,0.710195,AAAA,0.710195,0.433392,0.634988,0.307869,0.223498,...,0.347195,0.349190,0.303696,0.310790,0.346881,0.321472,0.308044,0.290831,0.448359,0.388990
4,5,Q28278,456,0.705648,DAAD,0.285025,0.390098,0.451574,0.400482,0.286399,...,0.466489,0.304141,0.378106,0.705648,0.381739,0.278645,0.426911,0.451948,0.440053,0.362939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1214,1215,Q89504,568,0.412353,DDDA,0.381894,0.346296,0.273213,0.363967,0.285818,...,0.267852,0.319979,0.385939,0.331831,0.242935,0.277175,0.388185,0.322473,0.412353,0.373821
1215,1216,E7BAR3,581,0.408235,AAAA,0.408235,0.383973,0.321834,0.322990,0.378860,...,0.280850,0.378739,0.380688,0.301842,0.338597,0.252217,0.387749,0.379218,0.281888,0.384788
1216,1217,A6TEP2,455,0.406265,DDDA,0.345258,0.266788,0.384372,0.385949,0.397235,...,0.237625,0.289363,0.358554,0.387324,0.342490,0.385267,0.358895,0.280707,0.406265,0.403278
1217,1218,P58371,536,0.402204,AADA,0.289796,0.384406,0.402204,0.352460,0.293018,...,0.250101,0.307452,0.305608,0.385235,0.388395,0.286248,0.366128,0.341487,0.325643,0.384271
1218,1219,A9EJ70,589,0.401103,ADAD,0.313745,0.398646,0.362170,0.397146,0.388184,...,0.391319,0.388589,0.281141,0.393656,0.382992,0.247204,0.341122,0.344426,0.308634,0.322804

In [11]:
result = merops.merge(ser[:500], left_on= 'UniProt_ID', right_on='accession')

In [14]:
result

,Unnamed: 0,UniProt_ID,MEROPS_ID,rank,accession,length,C,best_band,AAAA,AAAD,...,ADDA,ADDD,DAAA,DAAD,DADA,DADD,DDAA,DDAD,DDDA,DDDD
0,57,A0JNK3,S01.278,271,A0JNK3,458,0.566325,AAAA,0.566325,0.321813,...,0.381749,0.287993,0.364050,0.299794,0.445250,0.459770,0.298431,0.432277,0.287760,0.337588
1,60,A6YFB5,S01.277,420,A6YFB5,459,0.541937,DADA,0.322652,0.345516,...,0.319815,0.338619,0.392007,0.490859,0.541937,0.415563,0.324990,0.396982,0.393226,0.394477
2,63,B0BNB9,S01.278,227,B0BNB9,458,0.575178,AAAA,0.575178,0.334863,...,0.398271,0.319149,0.450126,0.308471,0.385500,0.423282,0.408107,0.300728,0.398485,0.372047
3,64,G1PU69,S01.278,108,G1PU69,456,0.599190,AAAA,0.599190,0.351351,...,0.288618,0.295815,0.338007,0.360918,0.500530,0.341167,0.418478,0.438373,0.301958,0.350686
4,65,D2HH54,S01.278,222,D2HH54,458,0.575848,AAAA,0.575848,0.394814,...,0.378107,0.293623,0.401447,0.321841,0.459120,0.421591,0.401015,0.376423,0.294902,0.337958
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,42595,T0FCD4,S41.004,99,T0FCD4,456,0.601290,DAAD,0.312687,0.341475,...,0.541977,0.323250,0.363093,0.601290,0.381797,0.269612,0.417420,0.444038,0.447013,0.378415
496,42612,V5WCJ9,S41.004,485,V5WCJ9,495,0.534350,DAAD,0.429142,0.379933,...,0.330635,0.379411,0.492037,0.534350,0.377665,0.280251,0.451964,0.477707,0.335093,0.465288
497,42614,V6HXZ6,S41.004,411,V6HXZ6,462,0.542937,DDDA,0.303499,0.382325,...,0.502681,0.417698,0.367882,0.532954,0.378482,0.369694,0.440296,0.460174,0.542937,0.295448
498,42616,U5DKM5,S13.003,88,U5DKM5,464,0.606026,ADDD,0.385301,0.383740,...,0.373289,0.606026,0.401205,0.386639,0.420152,0.246044,0.316746,0.414640,0.391540,0.296659
499,42632,W5SZQ1,S41.013,375,W5SZQ1,474,0.548876,ADAA,0.289090,0.258005,...,0.460192,0.448095,0.544169,0.460889,0.261020,0.501352,0.367844,0.517953,0.379439,0.455692

In [23]:
mer = merops['MEROPS_ID']

In [24]:
import requests
import pandas as pd
import time
import re
from bs4 import BeautifulSoup


# ============================================================
# INPUT
# ============================================================

# Your existing list:
#
# mer = [
#     "S01.001",
#     "S01.002",
#     "M01.001",
#     ...
# ]


# ============================================================
# SETTINGS
# ============================================================

MEROPS_URL = "https://www.ebi.ac.uk/merops/cgi-bin/substrates"
UNIPROT_URL = "https://rest.uniprot.org/uniprotkb/{}.fasta"

WINDOW = 10
MEROPS_DELAY = 1.0


# ============================================================
# SESSION
# ============================================================

session = requests.Session()

session.headers.update({
    "User-Agent": "Mozilla/5.0 Protease-substrate research"
})


# ============================================================
# CACHE
# ============================================================

merops_cache = {}
sequence_cache = {}


# ============================================================
# GET MEROPS SUBSTRATE TABLE
# ============================================================

def get_merops_substrates(merops_id):

    if merops_id in merops_cache:
        return merops_cache[merops_id]

    try:

        response = session.get(
            MEROPS_URL,
            params={"id": merops_id},
            timeout=60
        )

        response.raise_for_status()

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        tables = soup.find_all("table")

        for table in tables:

            rows = table.find_all("tr")

            if not rows:
                continue

            headers = [
                cell.get_text(" ", strip=True)
                for cell in rows[0].find_all(
                    ["th", "td"]
                )
            ]

            # Find the substrate table
            substrate_column = None

            for i, header in enumerate(headers):

                if "substrate" in header.lower():

                    substrate_column = i
                    break

            if substrate_column is None:
                continue

            data = []

            for row in rows[1:]:

                cells = [
                    cell.get_text(" ", strip=True)
                    for cell in row.find_all(
                        ["td", "th"]
                    )
                ]

                if len(cells) <= substrate_column:
                    continue

                # Keep the complete row
                if len(cells) < len(headers):
                    cells += [""] * (
                        len(headers) - len(cells)
                    )

                cells = cells[:len(headers)]

                row_dict = dict(
                    zip(headers, cells)
                )

                data.append(row_dict)

            merops_cache[merops_id] = data

            return data

        merops_cache[merops_id] = []

        return []

    except Exception as e:

        print(
            f"MEROPS ERROR {merops_id}: {e}"
        )

        merops_cache[merops_id] = []

        return []


# ============================================================
# GENERIC COLUMN FINDER
# ============================================================

def get_column(row, possible_names):

    normalized = {}

    for key in row.keys():

        clean = re.sub(
            r"[^a-z0-9]",
            "",
            str(key).lower()
        )

        normalized[clean] = key

    for name in possible_names:

        clean = re.sub(
            r"[^a-z0-9]",
            "",
            name.lower()
        )

        if clean in normalized:

            value = row[normalized[clean]]

            if value is not None:
                return str(value).strip()

    return ""


# ============================================================
# GET SUBSTRATE UniProt ID
# ============================================================

def get_substrate_uniprot(row):

    value = get_column(
        row,
        [
            "UniProt",
            "Uniprot",
            "UniProt ID",
            "UniProt accession",
            "Accession"
        ]
    )

    # Some MEROPS entries may contain additional text.
    # Try to extract a standard UniProt accession.

    match = re.search(
        r"\b[A-NR-Z][0-9][A-Z0-9]{3}[0-9]\b",
        value
    )

    if match:
        return match.group(0)

    return value


# ============================================================
# GET SUBSTRATE SEQUENCE FROM UniProt
# ============================================================

def get_uniprot_sequence(uniprot_id):

    if not uniprot_id:
        return None

    if uniprot_id in sequence_cache:
        return sequence_cache[uniprot_id]

    try:

        # Remove isoform suffix if present
        # e.g. P12345-2 -> P12345
        base_id = uniprot_id.split("-")[0]

        url = UNIPROT_URL.format(
            base_id
        )

        response = session.get(
            url,
            timeout=60
        )

        if response.status_code != 200:

            sequence_cache[uniprot_id] = None

            return None

        sequence = "".join(
            line.strip()
            for line in response.text.splitlines()
            if not line.startswith(">")
        )

        sequence_cache[
            uniprot_id
        ] = sequence

        return sequence

    except Exception as e:

        print(
            f"UniProt ERROR {uniprot_id}: {e}"
        )

        sequence_cache[
            uniprot_id
        ] = None

        return None


# ============================================================
# PARSE CLEAVAGE POSITION
# ============================================================

def parse_cleavage_position(cleavage_site):

    if not cleavage_site:
        return None

    # Examples:
    #
    # Gly373+Ala
    # Arg195+Ser
    # Lys1754+Ser
    #
    # The number corresponds to P1.

    match = re.search(
        r"[A-Za-z]{1,3}[- ]?(\d+)\s*\+",
        cleavage_site
    )

    if match:

        return int(
            match.group(1)
        )

    return None


# ============================================================
# EXTRACT ±10 AA WINDOW
# ============================================================

def get_binding_window(
    sequence,
    cleavage_position,
    window=10
):

    if (
        not sequence
        or cleavage_position is None
    ):
        return None

    # MEROPS uses 1-based residue numbering.
    #
    # If cleavage is:
    #
    # residue 100 | residue 101
    #       P1    |    P1'
    #
    # Python cleavage boundary = index 100

    cut_index = cleavage_position

    left = max(
        0,
        cut_index - window
    )

    right = min(
        len(sequence),
        cut_index + window
    )

    region = sequence[
        left:right
    ]

    marker = cut_index - left

    return (
        region[:marker]
        + "|"
        + region[marker:]
    )


# ============================================================
# MAIN LOOP
# ============================================================

results = []

failed_merops = []

for i, merops_id in enumerate(
    mer,
    start=1
):

    print(
        f"[{i}/{len(mer)}] {merops_id}"
    )

    # --------------------------------------------------------
    # Get substrate records
    # --------------------------------------------------------

    substrates = get_merops_substrates(
        merops_id
    )

    print(
        f"    {len(substrates)} substrate records"
    )

    if not substrates:
        failed_merops.append(
            merops_id
        )

    # --------------------------------------------------------
    # Process every substrate
    # --------------------------------------------------------

    for substrate in substrates:

        # ----------------------------------------------------
        # Substrate information
        # ----------------------------------------------------

        substrate_name = get_column(
            substrate,
            [
                "Substrate",
                "Substrate name"
            ]
        )

        substrate_uniprot = (
            get_substrate_uniprot(
                substrate
            )
        )

        # ----------------------------------------------------
        # Cleavage site
        # ----------------------------------------------------

        cleavage_site = get_column(
            substrate,
            [
                "Cleavage Site",
                "Cleavage",
                "Site"
            ]
        )

        # ----------------------------------------------------
        # Get full substrate sequence
        # ----------------------------------------------------

        substrate_sequence = None

        if substrate_uniprot:

            substrate_sequence = (
                get_uniprot_sequence(
                    substrate_uniprot
                )
            )

        # ----------------------------------------------------
        # Synthetic substrate
        #
        # If there is no UniProt sequence, look for a
        # sequence directly in the MEROPS record.
        # ----------------------------------------------------

        if not substrate_sequence:

            substrate_sequence = get_column(
                substrate,
                [
                    "Sequence",
                    "Substrate sequence",
                    "Peptide sequence"
                ]
            )

            if not substrate_sequence:
                substrate_sequence = None

        # ----------------------------------------------------
        # Cleavage position
        # ----------------------------------------------------

        cleavage_position = (
            parse_cleavage_position(
                cleavage_site
            )
        )

        # ----------------------------------------------------
        # ±10 AA sequence
        # ----------------------------------------------------

        binding_window = (
            get_binding_window(
                substrate_sequence,
                cleavage_position,
                WINDOW
            )
        )

        # ----------------------------------------------------
        # Store result
        # ----------------------------------------------------

        results.append({

            "merops_id":
                merops_id,

            "substrate":
                substrate_name,

            "substrate_uniprot":
                substrate_uniprot,

            "substrate_sequence":
                substrate_sequence,

            "cleavage_site":
                cleavage_site,

            "cleavage_position":
                cleavage_position,

            "binding_window_±10":
                binding_window
        })

    # --------------------------------------------------------
    # Delay before next MEROPS request
    # --------------------------------------------------------

    time.sleep(
        MEROPS_DELAY
    )


# ============================================================
# CREATE DATAFRAME
# ============================================================

df = pd.DataFrame(
    results
)


# ============================================================
# SAVE
# ============================================================

df.to_csv(
    "merops_substrates_with_window10.csv",
    index=False
)


# ============================================================
# SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("FINISHED")
print("=" * 70)

print(
    "MEROPS IDs:",
    len(mer)
)

print(
    "Total substrate records:",
    len(df)
)

print(
    "Records with substrate sequence:",
    df["substrate_sequence"].notna().sum()
)

print(
    "Records with ±10 AA window:",
    df["binding_window_±10"].notna().sum()
)

print(
    "MEROPS IDs with no substrate records:",
    len(failed_merops)
)

print(
    "\nCSV:",
    "merops_substrates_with_window10.csv"
)

display(
    df.head(20)
)

[1/1220] S01.278
    235 substrate records
[2/1220] S01.277
    5 substrate records
[3/1220] S01.278
    235 substrate records
[4/1220] S01.278
    235 substrate records
[5/1220] S01.278
    235 substrate records
[6/1220] S01.278
    235 substrate records
[7/1220] S01.278
    235 substrate records
[8/1220] S41.002
    2 substrate records
[9/1220] S01.278
    235 substrate records
[10/1220] S01.216
    63 substrate records
[11/1220] S01.278
    235 substrate records
[12/1220] S01.278
    235 substrate records
[13/1220] S01.494
    39 substrate records
[14/1220] S01.278
    235 substrate records
[15/1220] S01.214
    12 substrate records
[16/1220] S01.278
    235 substrate records
[17/1220] S01.216
    63 substrate records
[18/1220] S01.247
    21 substrate records
[19/1220] S01.278
    235 substrate records
[20/1220] S41.007
    18 substrate records
[21/1220] S01.232
    9 substrate records
[22/1220] S01.202
    0 substrate records
[23/1220] S01.199
    7 substrate records
[24/1220] S08.051
    11 substrate records
[25/1220] S08.055
    0 substrate records
[26/1220] S01.216
    63 substrate records
[27/1220] S01.273
    16 substrate records
[28/1220] S01.214
    12 substrate records
[29/1220] S01.216
    63 substrate records
[30/1220] S01.214
    12 substrate records
[31/1220] S01.214
    12 substrate records
[32/1220] S01.214
    12 substrate records
[33/1220] S01.218
    15 substrate records
[34/1220] S01.214
    12 substrate records
[35/1220] S13.001
    1 substrate records
[36/1220] S01.218
    15 substrate records
[37/1220] S01.215
    9 substrate records
[38/1220] S01.426
    0 substrate records
[39/1220] S01.425
    4 substrate records
[40/1220] S01.079
    1 substrate records
[41/1220] S33.023
    5 substrate records
[42/1220] S01.284
    0 substrate records
[43/1220] S01.285
    0 substrate records
[44/1220] S33.023
    5 substrate records
[45/1220] S01.426
    0 substrate records
[46/1220] S01.232
    9 substrate records
[47/1220] S01.218
    15 substrate records
[48/1220] S01.239
    1 substrate records
[49/1220] S01.218
    15 substrate records
[50/1220] S08.132
    0 substrate records
[51/1220] S01.215
    9 substrate records
[52/1220] S01.033
    15 substrate records
[53/1220] S08.143
    0 substrate records
[54/1220] S21.006
    2 substrate records
[55/1220] S01.215
    9 substrate records
[56/1220] S01.278
    235 substrate records
[57/1220] S01.218
    15 substrate records
[58/1220] S01.425
    4 substrate records
[59/1220] S01.446
    9 substrate records
[60/1220] S01.218
    15 substrate records
[61/1220] S01.286
    1 substrate records
[62/1220] S08.102
    3 substrate records
[63/1220] S01.214
    12 substrate records
[64/1220] S01.396
    0 substrate records
[65/1220] S01.087
    4 substrate records
[66/1220] S01.446
    9 substrate records
[67/1220] S01.214
    12 substrate records
[68/1220] S01.216
    63 substrate records
[69/1220] S01.446
    9 substrate records
[70/1220] S01.320
    0 substrate records
[71/1220] S53.009
    1 substrate records
[72/1220] S53.006
    11 substrate records
[73/1220] S39.001
    5 substrate records
[74/1220] S01.277
    5 substrate records
[75/1220] S01.079
    1 substrate records
[76/1220] S01.214
    12 substrate records
[77/1220] S01.313
    2 substrate records
[78/1220] S53.004
    11 substrate records
[79/1220] S01.286
    1 substrate records
[80/1220] S01.247
    21 substrate records
[81/1220] S01.189
    1 substrate records
[82/1220] S01.087
    4 substrate records
[83/1220] S01.278
    235 substrate records
[84/1220] S01.284
    0 substrate records
[85/1220] S01.277
    5 substrate records
[86/1220] S01.277
    5 substrate records
[87/1220] S01.218
    15 substrate records
[88/1220] S01.281
    11 substrate records
[89/1220] S01.277
    5 substrate records
[90/1220] S01.396
    0 substrate records
[91/1220] S21.006
    2 substrate records
[92/1220] S21.006
    2 substrate records
[93/1220] S21.006
    2 substrate records
[94/1220] S01.396
    0 substrate records
[95/1220] S01.425
    4 substrate records
[96/1220] S21.001
    5 substrate records
[97/1220] S41.A02
    0 substrate records
[98/1220] S01.232
    9 substrate records
[99/1220] S01.218
    15 substrate records
[100/1220] S21.006
    2 substrate records
[101/1220] S01.232
    9 substrate records
[102/1220] S01.232
    9 substrate records
[103/1220] S01.232
    9 substrate records
[104/1220] S01.218
    15 substrate records
[105/1220] S08.102
    3 substrate records
[106/1220] S21.006
    2 substrate records
[107/1220] S21.006
    2 substrate records
[108/1220] S21.004
    4 substrate records
[109/1220] S41.002
    2 substrate records
[110/1220] S01.273
    16 substrate records
[111/1220] S21.006
    2 substrate records
[112/1220] S01.239
    1 substrate records
[113/1220] S21.006
    2 substrate records
[114/1220] S21.001
    5 substrate records
[115/1220] S21.004
    4 substrate records
[116/1220] S01.273
    16 substrate records
[117/1220] S21.004
    4 substrate records
[118/1220] S08.A54
    0 substrate records
[119/1220] S08.A50
    0 substrate records
[120/1220] S13.001
    1 substrate records
[121/1220] S01.265
    1 substrate records
[122/1220] S21.004
    4 substrate records
[123/1220] S21.006
    2 substrate records
[124/1220] S01.446
    9 substrate records
[125/1220] S21.006
    2 substrate records
[126/1220] S01.396
    0 substrate records
[127/1220] S01.375
    0 substrate records
[128/1220] S21.006
    2 substrate records
[129/1220] S01.396
    0 substrate records
[130/1220] S21.006
    2 substrate records
[131/1220] S01.033
    15 substrate records
[132/1220] S01.284
    0 substrate records
[133/1220] S01.218
    15 substrate records
[134/1220] S01.199
    7 substrate records
[135/1220] S01.232
    9 substrate records
[136/1220] S21.001
    5 substrate records
[137/1220] S21.001
    5 substrate records
[138/1220] S01.033
    15 substrate records
[139/1220] S21.001
    5 substrate records
[140/1220] S01.218
    15 substrate records
[141/1220] S21.006
    2 substrate records
[142/1220] S21.001
    5 substrate records
[143/1220] S21.001
    5 substrate records
[144/1220] S21.006
    2 substrate records
[145/1220] S21.006
    2 substrate records
[146/1220] S01.033
    15 substrate records
[147/1220] S01.232
    9 substrate records
[148/1220] S21.004
    4 substrate records
[149/1220] S21.006
    2 substrate records
[150/1220] S54.010
    0 substrate records
[151/1220] S21.005
    2 substrate records
[152/1220] S21.006
    2 substrate records
[153/1220] S01.313
    2 substrate records
[154/1220] S01.B81
    0 substrate records
[155/1220] S21.006
    2 substrate records
[156/1220] S21.006
    2 substrate records
[157/1220] S01.232
    9 substrate records
[158/1220] S01.215
    9 substrate records
[159/1220] S01.214
    12 substrate records
[160/1220] S01.215
    9 substrate records
[161/1220] S01.329
    0 substrate records
[162/1220] S01.214
    12 substrate records
[163/1220] S01.453
    0 substrate records
[164/1220] S01.273
    16 substrate records
[165/1220] S01.274
    7 substrate records
[166/1220] S01.278
    235 substrate records
[167/1220] S01.214
    12 substrate records
[168/1220] S01.199
    7 substrate records
[169/1220] S16.005
    0 substrate records
[170/1220] S01.453
    0 substrate records
[171/1220] S01.216
    63 substrate records
[172/1220] S01.453
    0 substrate records
[173/1220] S01.216
    63 substrate records
[174/1220] S01.453
    0 substrate records
[175/1220] S01.232
    9 substrate records
[176/1220] S01.B33
    0 substrate records
[177/1220] S01.139
    1369 substrate records
[178/1220] S01.232
    9 substrate records
[179/1220] S01.218
    15 substrate records
[180/1220] S01.232
    9 substrate records
[181/1220] S01.273
    16 substrate records
[182/1220] S01.216
    63 substrate records
[183/1220] S01.274
    7 substrate records
[184/1220] S01.232
    9 substrate records
[185/1220] S01.239
    1 substrate records
[186/1220] S01.274
    7 substrate records
[187/1220] S08.025
    2 substrate records
[188/1220] S01.274
    7 substrate records
[189/1220] S01.274
    7 substrate records
[190/1220] S01.273
    16 substrate records
[191/1220] S08.025
    2 substrate records
[192/1220] S01.273
    16 substrate records
[193/1220] S01.232
    9 substrate records
[194/1220] S01.274
    7 substrate records
[195/1220] S01.453
    0 substrate records
[196/1220] S01.453
    0 substrate records
[197/1220] S54.A16
MEROPS ERROR S54.A16: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
    0 substrate records
[198/1220] S01.196
    8 substrate records
[199/1220] S08.135
    19 substrate records
[200/1220] S08.025
    2 substrate records
[201/1220] S01.274
    7 substrate records
[202/1220] S01.231
    19 substrate records
[203/1220] S08.049
    4 substrate records
[204/1220] S01.453
    0 substrate records
[205/1220] S01.218
    15 substrate records
[206/1220] S08.062
    0 substrate records
[207/1220] S01.232
    9 substrate records
[208/1220] S01.217
    195 substrate records
[209/1220] S01.214
    12 substrate records
[210/1220] S01.274
    7 substrate records
[211/1220] S01.214
    12 substrate records
[212/1220] S41.A01
    0 substrate records
[213/1220] S01.247
    21 substrate records
[214/1220] S01.214
    12 substrate records
[215/1220] S01.216
    63 substrate records
[216/1220] S01.214
    12 substrate records
[217/1220] S01.247
    21 substrate records
[218/1220] S01.224
    110 substrate records
[219/1220] S01.214
    12 substrate records
[220/1220] S01.232
    9 substrate records
[221/1220] S01.211
    7 substrate records
[222/1220] S01.232
    9 substrate records
[223/1220] S01.231
    19 substrate records
[224/1220] S01.216
    63 substrate records
[225/1220] S01.218
    15 substrate records
[226/1220] S01.216
    63 substrate records
[227/1220] S01.216
    63 substrate records
[228/1220] S01.247
    21 substrate records
[229/1220] S01.396
    0 substrate records
[230/1220] S01.199
    7 substrate records
[231/1220] S01.214
    12 substrate records
[232/1220] S01.216
    63 substrate records
[233/1220] S01.232
    9 substrate records
[234/1220] S08.135
    19 substrate records
[235/1220] S01.453
    0 substrate records
[236/1220] S01.215
    9 substrate records
[237/1220] S01.247
    21 substrate records
[238/1220] S01.033
    15 substrate records
[239/1220] S01.218
    15 substrate records
[240/1220] S01.214
    12 substrate records
[241/1220] S01.218
    15 substrate records
[242/1220] S01.199
    7 substrate records
[243/1220] S01.218
    15 substrate records
[244/1220] S01.215
    9 substrate records
[245/1220] S01.216
    63 substrate records
[246/1220] S01.247
    21 substrate records
[247/1220] S01.216
    63 substrate records
[248/1220] S01.247
    21 substrate records
[249/1220] S01.214
    12 substrate records
[250/1220] S01.194
    9 substrate records
[251/1220] S01.453
    0 substrate records
[252/1220] S01.214
    12 substrate records
[253/1220] S01.216
    63 substrate records
[254/1220] S01.199
    7 substrate records
[255/1220] S01.232
    9 substrate records
[256/1220] S01.214
    12 substrate records
[257/1220] S01.194
    9 substrate records
[258/1220] S01.214
    12 substrate records
[259/1220] S01.216
    63 substrate records
[260/1220] S01.396
    0 substrate records
[261/1220] S01.217
    195 substrate records
[262/1220] S01.216
    63 substrate records
[263/1220] S01.033
    15 substrate records
[264/1220] S01.218
    15 substrate records
[265/1220] S01.239
    1 substrate records
[266/1220] S01.217
    195 substrate records
[267/1220] S01.425
    4 substrate records
[268/1220] S01.232
    9 substrate records
[269/1220] S01.232
    9 substrate records
[270/1220] S01.396
    0 substrate records
[271/1220] S01.216
    63 substrate records
[272/1220] S01.194
    9 substrate records
[273/1220] S01.216
    63 substrate records
[274/1220] S01.199
    7 substrate records
[275/1220] S01.214
    12 substrate records
[276/1220] S01.216
    63 substrate records
[277/1220] S41.010
    0 substrate records
[278/1220] S01.232
    9 substrate records
[279/1220] S01.218
    15 substrate records
[280/1220] S01.278
    235 substrate records
[281/1220] S01.232
    9 substrate records
[282/1220] S01.231
    19 substrate records
[283/1220] S01.218
    15 substrate records
[284/1220] S01.278
    235 substrate records
[285/1220] S01.189
    1 substrate records
[286/1220] S01.214
    12 substrate records
[287/1220] S08.131
    0 substrate records
[288/1220] S01.453
    0 substrate records
[289/1220] S41.007
    18 substrate records
[290/1220] S08.131
    0 substrate records
[291/1220] S01.480
    14 substrate records
[292/1220] S08.102
    3 substrate records
[293/1220] S08.A51
    0 substrate records
[294/1220] S49.003
    1 substrate records
[295/1220] S16.005
    0 substrate records
[296/1220] S08.052
    21 substrate records
[297/1220] S33.023
    5 substrate records
[298/1220] S01.278
    235 substrate records
[299/1220] S01.281
    11 substrate records
[300/1220] S01.216
    63 substrate records
[301/1220] S01.276
    5 substrate records
[302/1220] S01.216
    63 substrate records
[303/1220] S01.215
    9 substrate records
[304/1220] S01.453
    0 substrate records
[305/1220] S01.232
    9 substrate records
[306/1220] S01.216
    63 substrate records
[307/1220] S01.216
    63 substrate records
[308/1220] S01.453
    0 substrate records
[309/1220] S01.216
    63 substrate records
[310/1220] S01.189
    1 substrate records
[311/1220] S01.453
    0 substrate records
[312/1220] S01.239
    1 substrate records
[313/1220] S01.453
    0 substrate records
[314/1220] S01.453
    0 substrate records
[315/1220] S01.218
    15 substrate records
[316/1220] S01.274
    7 substrate records
[317/1220] S01.216
    63 substrate records
[318/1220] S08.071
    220 substrate records
[319/1220] S01.273
    16 substrate records
[320/1220] S01.189
    1 substrate records
[321/1220] S08.025
    2 substrate records
[322/1220] S01.453
    0 substrate records
[323/1220] S01.216
    63 substrate records
[324/1220] S01.247
    21 substrate records
[325/1220] S01.278
    235 substrate records
[326/1220] S01.232
    9 substrate records
[327/1220] S01.217
    195 substrate records
[328/1220] S01.232
    9 substrate records
[329/1220] S01.425
    4 substrate records
[330/1220] S01.199
    7 substrate records
[331/1220] S01.453
    0 substrate records
[332/1220] S08.032
    4 substrate records
[333/1220] S08.062
    0 substrate records
[334/1220] S08.135
    19 substrate records
[335/1220] S01.214
    12 substrate records
[336/1220] S01.453
    0 substrate records
[337/1220] S01.A06
    0 substrate records
[338/1220] S01.453
    0 substrate records
[339/1220] S01.A03
    0 substrate records
[340/1220] S01.A01
    0 substrate records
[341/1220] S01.A04
    0 substrate records
[342/1220] S01.A07
    0 substrate records
[343/1220] S01.480
    14 substrate records
[344/1220] S01.A02
    0 substrate records
[345/1220] S08.032
    4 substrate records
[346/1220] S01.453
    0 substrate records
[347/1220] S01.217
    195 substrate records
[348/1220] S01.B33
    0 substrate records
[349/1220] S01.232
    9 substrate records
[350/1220] S01.214
    12 substrate records
[351/1220] S01.453
    0 substrate records
[352/1220] S01.232
    9 substrate records
[353/1220] S41.001
    9 substrate records
[354/1220] S16.005
    0 substrate records
[355/1220] S13.001
    1 substrate records
[356/1220] S41.A01
    0 substrate records
[357/1220] S13.001
    1 substrate records
[358/1220] S01.A48
    0 substrate records
[359/1220] S01.A80
    0 substrate records
[360/1220] S41.A01
    0 substrate records
[361/1220] S41.A01
    0 substrate records
[362/1220] S41.A01
    0 substrate records
[363/1220] S41.A02
    0 substrate records
[364/1220] S41.002
    2 substrate records
[365/1220] S41.A01
    0 substrate records
[366/1220] S41.A02
    0 substrate records
[367/1220] S41.002
    2 substrate records
[368/1220] S41.002
    2 substrate records
[369/1220] S41.A02
    0 substrate records
[370/1220] S09.010
    42 substrate records
[371/1220] S41.A02
    0 substrate records
[372/1220] S41.A01
    0 substrate records
[373/1220] S41.007
    18 substrate records
[374/1220] S13.001
    1 substrate records
[375/1220] S41.A01
    0 substrate records
[376/1220] S41.A02
    0 substrate records
[377/1220] S41.A01
    0 substrate records
[378/1220] S01.453
    0 substrate records
[379/1220] S16.005
    0 substrate records
[380/1220] S16.A10
    0 substrate records
[381/1220] S01.274
    7 substrate records
[382/1220] S41.A02
    0 substrate records
[383/1220] S01.453
    0 substrate records
[384/1220] S26.010
    363 substrate records
[385/1220] S41.002
    2 substrate records
[386/1220] S41.A02
    0 substrate records
[387/1220] S41.A01
    0 substrate records
[388/1220] S08.073
    205 substrate records
[389/1220] S08.073
    205 substrate records
[390/1220] S01.228
    2 substrate records
[391/1220] S01.231
    19 substrate records
[392/1220] S13.001
    1 substrate records
[393/1220] S13.001
    1 substrate records
[394/1220] S01.B81
    0 substrate records
[395/1220] S08.073
    205 substrate records
[396/1220] S08.073
    205 substrate records
[397/1220] S01.247
    21 substrate records
[398/1220] S08.073
    205 substrate records
[399/1220] S08.073
    205 substrate records
[400/1220] S01.232
    9 substrate records
[401/1220] S08.073
    205 substrate records
[402/1220] S08.073
    205 substrate records
[403/1220] S08.073
    205 substrate records
[404/1220] S08.073
    205 substrate records
[405/1220] S08.073
    205 substrate records
[406/1220] S08.073
    205 substrate records
[407/1220] S08.073
    205 substrate records
[408/1220] S08.073
    205 substrate records
[409/1220] S08.073
    205 substrate records
[410/1220] S08.073
    205 substrate records
[411/1220] S08.073
    205 substrate records
[412/1220] S08.073
    205 substrate records
[413/1220] S08.073
    205 substrate records
[414/1220] S41.004
    0 substrate records
[415/1220] S13.001
    1 substrate records
[416/1220] S01.216
    63 substrate records
[417/1220] S01.286
    1 substrate records
[418/1220] S13.001
    1 substrate records
[419/1220] S16.A10
    0 substrate records
[420/1220] S08.073
    205 substrate records
[421/1220] S08.073
    205 substrate records
[422/1220] S41.A01
    0 substrate records
[423/1220] S41.002
    2 substrate records
[424/1220] S41.A02
    0 substrate records
[425/1220] S13.001
    1 substrate records
[426/1220] S41.002
    2 substrate records
[427/1220] S41.A01
    0 substrate records
[428/1220] S41.A02
    0 substrate records
[429/1220] S41.A01
    0 substrate records
[430/1220] S01.B57
    0 substrate records
[431/1220] S01.453
    0 substrate records
[432/1220] S16.005
    0 substrate records
[433/1220] S41.007
    18 substrate records
[434/1220] S41.004
    0 substrate records
[435/1220] S41.002
    2 substrate records
[436/1220] S41.A02
    0 substrate records
[437/1220] S41.A01
    0 substrate records
[438/1220] S41.A02
    0 substrate records
[439/1220] S41.A02
    0 substrate records
[440/1220] S41.002
    2 substrate records
[441/1220] S41.002
    2 substrate records
[442/1220] S41.A01
    0 substrate records
[443/1220] S41.A02
    0 substrate records
[444/1220] S16.005
    0 substrate records
[445/1220] S41.A02
    0 substrate records
[446/1220] S41.A02
    0 substrate records
[447/1220] S41.002
    2 substrate records
[448/1220] S41.A02
    0 substrate records
[449/1220] S41.A02
    0 substrate records
[450/1220] S41.A02
    0 substrate records
[451/1220] S13.003
    0 substrate records
[452/1220] S41.004
    0 substrate records
[453/1220] S26.010
    363 substrate records
[454/1220] S01.A80
    0 substrate records
[455/1220] S01.364
    2 substrate records
[456/1220] S41.007
    18 substrate records
[457/1220] S01.274
    7 substrate records
[458/1220] S41.004
    0 substrate records
[459/1220] S08.136
    0 substrate records
[460/1220] S16.005

,merops_id,substrate,substrate_uniprot,substrate_sequence,cleavage_site,cleavage_position,binding_window_±10
0,S01.278,3-hydroxyacyl-CoA dehydrogenase type-2,Q99714,MAAACRSVKGLVAVITGGASGLGLATAERLVGQGASAVLLDLPNSG...,peptide-Cys58+Val-peptide,58.0,AQAKKLGNNC|VFAPADVTSE
1,S01.278,"Actin, alpha cardiac muscle 1",P68032,MCDDEETTALVCDNGSGLVKAGFAGDDAPRAVFPSIVGRPRHQGVM...,peptide-Val19+Lys-peptide,19.0,LVCDNGSGLV|KAGFAGDDAP
2,S01.278,"Actin, alpha cardiac muscle 1",P68032,MCDDEETTALVCDNGSGLVKAGFAGDDAPRAVFPSIVGRPRHQGVM...,peptide-Leu107+Thr-peptide,107.0,VAPEEHPTLL|TEAPLNPKAN
3,S01.278,"Actin, alpha cardiac muscle 1",P68032,MCDDEETTALVCDNGSGLVKAGFAGDDAPRAVFPSIVGRPRHQGVM...,peptide-Thr108+Glu-peptide,108.0,APEEHPTLLT|EAPLNPKANR
4,S01.278,"actin, alpha skeletal muscle",P68133,MCDEDETTALVCDNGSGLVKAGFAGDDAPRAVFPSIVGRPRHQGVM...,peptide-Val19+Lys-peptide,19.0,LVCDNGSGLV|KAGFAGDDAP
5,S01.278,"actin, alpha skeletal muscle",P68133,MCDEDETTALVCDNGSGLVKAGFAGDDAPRAVFPSIVGRPRHQGVM...,peptide-Leu107+Thr-peptide,107.0,VAPEEHPTLL|TEAPLNPKAN
6,S01.278,"actin, alpha skeletal muscle",P68133,MCDEDETTALVCDNGSGLVKAGFAGDDAPRAVFPSIVGRPRHQGVM...,peptide-Val221+Ala-peptide,221.0,RDIKEKLCYV|ALDFENEMAT
7,S01.278,"actin, alpha skeletal muscle",P68133,MCDEDETTALVCDNGSGLVKAGFAGDDAPRAVFPSIVGRPRHQGVM...,peptide-Thr108+Glu-peptide,108.0,APEEHPTLLT|EAPLNPKANR
8,S01.278,"Actin, aortic smooth muscle",P62736,MCEEEDSTALVCDNGSGLCKAGFAGDDAPRAVFPSIVGRPRHQGVM...,peptide-Cys19+Lys-peptide,19.0,LVCDNGSGLC|KAGFAGDDAP
9,S01.278,"Actin, aortic smooth muscle",P62736,MCEEEDSTALVCDNGSGLCKAGFAGDDAPRAVFPSIVGRPRHQGVM...,peptide-Leu107+Thr-peptide,107.0,VAPEEHPTLL|TEAPLNPKAN
10,S01.278,"Actin, aortic smooth muscle",P62736,MCEEEDSTALVCDNGSGLCKAGFAGDDAPRAVFPSIVGRPRHQGVM...,peptide-Thr108+Glu-peptide,108.0,APEEHPTLLT|EAPLNPKANR
11,S01.278,"Actin, cytoplasmic 1",P60709,MDDDIAALVVDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVG...,peptide-Cys17+Lys-peptide,17.0,LVVDNGSGMC|KAGFAGDDAP
12,S01.278,"Actin, cytoplasmic 1",P60709,MDDDIAALVVDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVG...,peptide-Leu105+Thr-peptide,105.0,VAPEEHPVLL|TEAPLNPKAN
13,S01.278,"Actin, cytoplasmic 1",P60709,MDDDIAALVVDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVG...,peptide-Thr106+Glu-peptide,106.0,APEEHPVLLT|EAPLNPKANR
14,S01.278,"Actin, cytoplasmic 1",P60709,MDDDIAALVVDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVG...,peptide-Val219+Ala-peptide,219.0,RDIKEKLCYV|ALDFEQEMAT
15,S01.278,"Actin, cytoplasmic 2",P63261,MEEEIAALVIDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVG...,peptide-Cys17+Lys-peptide,17.0,LVIDNGSGMC|KAGFAGDDAP
16,S01.278,"Actin, cytoplasmic 2",P63261,MEEEIAALVIDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVG...,peptide-Leu105+Thr-peptide,105.0,VAPEEHPVLL|TEAPLNPKAN
17,S01.278,"Actin, cytoplasmic 2",P63261,MEEEIAALVIDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVG...,peptide-Thr106+Glu-peptide,106.0,APEEHPVLLT|EAPLNPKANR
18,S01.278,"Actin, cytoplasmic 2",P63261,MEEEIAALVIDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVG...,peptide-Val219+Ala-peptide,219.0,RDIKEKLCYV|ALDFEQEMAT
19,S01.278,"Actin, gamma-enteric smooth muscle",P63267,MCEEETTALVCDNGSGLCKAGFAGDDAPRAVFPSIVGRPRHQGVMV...,peptide-Cys18+Lys-peptide,18.0,LVCDNGSGLC|KAGFAGDDAP

In [27]:
df.to_csv(r"C:\Users\apkar\OneDrive\Documents\iGEM\Head\Linker design\Serine_Protease_Substrates.csv")

In [25]:
df['binding_window_±10'].nunique()

3758